### ISSUE TITLE
Inline style is not compatible with fixed

### ISSUE THREAD

**Issue by wslyvh** [thesephist/blocks.css#14]
Hi,

Awesome project! 
One thing I noticed though is that the inline style is not compatible with fixed.
Applying both means it still has all the behavior for interaction.

**Comment by thesephist** [comment]
Should be fixed by c7fadd73154b4ba1a4f111b48566f5f1aa280ed0 :) Just cut a new release to NPM so it should be live soon in v0.4.1.

Let me know if you run into any trouble!.

**Comment by wslyvh** [comment]
Awesome! Thanks for the quick turnaround :)
