### ISSUE TITLE
Unpkg cdn rate exceeded

### ISSUE THREAD

**Issue by grunklejp** [thesephist/blocks.css#4]
Buttons stopped working on a site I'm working on and it seems like you have exceeded your requests limit or something like that.

Sorry 🤭

[https://unpkg.com/blocks.css/dist/blocks.min.css](https://unpkg.com/blocks.css/dist/blocks.min.css)

**Comment by thesephist** [comment]
Ah -- I think this happens per-IP for unpkg, if you request the same file too many times from unpkg from the same browser / device. You can get around their rate limits by downloading your own copy of the CSS file and including it from your server instead of Unpkg.

**Comment by thesephist** [comment]
Going to close, since this issue isn't related to using Unpkg and not blocks.css itself, but feel free to ask follow-up questions in this thread!
